BUG: Fix GenericException assignment by using `shared_ptr` internally
SimpleITK/SimpleITK pull request #1669
Opened 2022-07-21 10:44 UTC by N-Dekker

The assignment operator of `GenericException` originally just copied the "raw" internal pointer (`m_PimpleException`), causing `delete` to be called twice on the very same pointer, when both the original and the copy of the GenericException are destructed. Which would have undefined behavior. Fixed by using `shared_ptr` instead of a raw pointer.

Used `= default` to implement its copy-constructor and its destructor, as `shared_ptr` now takes care of doing the right thing "by default".

2022-07-21 11:08 UTC, N-Dekker commented
FYI, the (originally troublesome) GenericException assignment operator is here:

https://github.com/SimpleITK/SimpleITK/blob/fb426f2811c7ef1853436168d3afdb72e9581b56/Code/Common/src/sitkExceptionObject.cxx#L99-L104 

The original destructor did unconditionally delete the internal pointer, potentially causing undefined behavior when one exception was assigned to another:

https://github.com/SimpleITK/SimpleITK/blob/fb426f2811c7ef1853436168d3afdb72e9581b56/Code/Common/src/sitkExceptionObject.cxx#L93-L96

2022-07-21 12:39 UTC, blowekamp commented
Nice fix! SimpleITK tries to follow best testing practices by adding regression tests for these types of bugs when they are encounter. Please add an appropriate test:
https://github.com/SimpleITK/SimpleITK/blob/master/Testing/Unit/sitkExceptionsTests.cxx

Also we don't use the ITK categories in the commit message. Please feel free to make the best use of those recovered characters in the the first line of the comment message.

2022-07-21 16:47 UTC, blowekamp requested changes
Please add testing.

2022-07-25 13:37 UTC, blowekamp approved these changes
Thank you for the fix and adding the test! Looks go to go.

2022-07-25 17:27 UTC, blowekamp commented
@N-Dekker Do you have permissions to hit the green merge button?

2022-07-25 20:37 UTC, N-Dekker commented
> Do you have permissions to hit the green merge button?

Yes, I think so, but I wouldn't mind if you press the button either 😄 It feels like a reward to me to see someone actually merging my pull request, rather than having to merge my own pull request, myself. But if necessary, yes I can merge my own PR! 

BTW Personally I would prefer the "Rebase and merge" option from the button, as it would avoid an extra "merge commit" in the git log history. But it appears that "Rebase and merge" is disabled, is that intentional?

2022-07-25 20:56 UTC, blowekamp commented
> Yes, I think so, but I wouldn't mind if you press the button either 😄 It feels like a reward to me to see someone actually merging my pull request, rather than having to merge my own pull request, myself. But if necessary, yes I can merge my own PR! 

OK I'll do it.

> BTW Personally I would prefer the "Rebase and merge" option from the button, as it would avoid an extra "merge commit" in the git log history. But it appears that "Rebase and merge" is disabled, is that intentional?

Yes.

2022-07-25 20:56 UTC, merged