Add Doxygen comments to all public `ElastixImageFilter` member functions
SimpleITK/SimpleITK pull request #1716
Opened 2022-09-16 14:11 UTC by N-Dekker

Part of issue https://github.com/SimpleITK/SimpleITK/issues/1665 "Update ElastixImageFilter and TransformixImageFilter Doxygen comments"

2022-09-16 15:36 UTC, blowekamp approved these changes
Looks good!

2022-09-16 15:42 UTC, zivy requested changes
Generally looks good. 

One thing that I am missing, how are the masks matched to the images, fixed or moving? For example if I have multiple moving images [MI1, MI2, MI3] and I want to add masks only to some of them [M1, none, M2] is that possible? Please add documentation explaining the constraints and expectations with respect to the information that should match between the various data containers (fixed_images, moving_images, fixed_masks, moving_masks). 

I suspect the following are expected, but not sure:
1.  size(fixed_images) == size(moving_images)
2. size(fixed_images) == size(fixed_masks), size(moving_images) == size(moving_masks).

2022-09-23 13:19 UTC, blowekamp commented
@N-Dekker Are you able to address Ziv's comments?

2022-09-23 13:24 UTC, N-Dekker commented
> Are you able to address Ziv's comments?

@blowekamp @zivy I'm still studying them. `ElastixImageFilterImpl::Execute` appears to check those constraints, starting here:

https://github.com/SimpleITK/SimpleITK/blob/ac3afb935291dc7830f370cb89ba54dea8e6d525/Code/ElastixTransformixWrappers/src/sitkElastixImageFilterImpl.cxx#L55-L59 

But I would need to check them myself, in order to document them properly.

2022-09-26 14:10 UTC, N-Dekker commented
@zivy Thansk for your comment. Just added a little note about those constraints to the documentation, with help from Marius (@mstaring). Hope it's sufficient for now, even if it may not yet be complete. The aim for this PR is just to add a _short_ description to each member function.

2022-09-27 13:32 UTC, zivy commented
Hello @N-Dekker, as a first pass on documentation this looks good. I'm sure there is more to be done, as always.

2022-09-27 13:32 UTC, zivy approved these changes

2022-09-27 14:30 UTC, blowekamp commented on Code/ElastixTransformixWrappers/include/sitkElastixImageFilter.h
> +   * /
The '* /' with the space seems to be causing a compilation error.
../../Code/ElastixTransformixWrappers/include/sitkElastixImageFilter.h:303:3: warning: "/*" within comment [-Wcomment]
[18351](https://github.com/SimpleITK/SimpleITK/actions/runs/3128399687/jobs/5076187945#step:6:18352)
  303 |   /** \brief Returns all transform parameter maps. */
[18352](https://github.com/SimpleITK/SimpleITK/actions/runs/3128399687/jobs/5076187945#step:6:18353)
      |    
[18353](https://github.com/SimpleITK/SimpleITK/actions/runs/3128399687/jobs/5076187945#step:6:18354)
../../Code/ElastixTransformixWrappers/src/sitkElastixImageFilter.cxx:621:1: error: no declaration matches ‘itk::simple::Image itk::simple::ElastixImageFilter::Execute()’
[18354](https://github.com/SimpleITK/SimpleITK/actions/runs/3128399687/jobs/5076187945#step:6:18355)
  621 | ElastixImageFilter
[18355](https://github.com/SimpleITK/SimpleITK/actions/runs/3128399687/jobs/5076187945#step:6:18356)
      | ^~~~~~~~~~~~~~~~~~

2022-10-10 12:04 UTC, merged